# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_planner', '0002_auto_20180408_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=256, null=True),
        ),
    ]
