# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-08 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_planner', '0002_auto_20180407_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='c_type',
            field=models.CharField(choices=[('C', 'COURSE'), ('S', 'SEMINAR'), ('L', 'LABORATORY')], default='C', max_length=1),
        ),
    ]
