# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_planner', '0003_group_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=256, null=True)),
                ('type', models.CharField(choices=[('F', 'FACULTY_DAY'), ('H', 'HOLY_DAY'), ('ES', 'EXAMS_SESSION'), ('ED', 'EXAMS_DEBT'), ('DBE', 'DISSERTATION_BACHELOR_EXAM'), ('PDBE', 'PREPARATION_DISSERTATION_BACHELOR_EXAM')], default='F', max_length=5)),
                ('detail', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('year', models.IntegerField()),
                ('final_years', models.BooleanField(default=False)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Year Structure',
                'verbose_name_plural': 'Year Structures',
            },
        ),
        migrations.CreateModel(
            name='YearStructureDayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holy_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_planner.DayType')),
                ('year_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_planner.YearStructure')),
            ],
        ),
        migrations.AddField(
            model_name='yearstructure',
            name='days',
            field=models.ManyToManyField(through='faculty_planner.YearStructureDayType', to='faculty_planner.DayType'),
        ),
    ]
