# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-08 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_planner', '0003_course_c_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedate',
            name='extra_info',
            field=models.CharField(default='', max_length=128),
        ),
    ]
