# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_planner', '0004_auto_20180514_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearstructure',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty_planner.Faculty'),
            preserve_default=False,
        ),
    ]
